export const GET_OFFER_REQUEST="GET_OFFER_REQUEST";
export const GET_OFFER_SUCCESS="GET_OFFER_SUCCESS";
export const GET_OFFER_FAIL="GET_OFFER_FAIL";

export const GET_OFFER_BY_ID_REQUEST="GET_OFFER_BY_ID_REQUEST";
export const GET_OFFER_BY_ID_SUCCESS="GET_OFFER_BY_ID_SUCCESS";
export const GET_OFFER_BY_ID_FAIL="GET_OFFER_BY_ID_FAIL";

export const CREATE_OFFER_REQUEST="CREATE_OFFER_REQUEST";
export const CREATE_OFFER_SUCCESS="CREATE_OFFER_SUCCESS";
export const CREATE_OFFER_FAIL="CREATE_OFFER_FAIL";

export const UPDATE_OFFER_REQUEST="UPDATE_OFFER_REQUEST";
export const UPDATE_OFFER_SUCCESS="UPDATE_OFFER_SUCCESS";
export const UPDATE_OFFER_FAIL="UPDATE_OFFER_FAIL";

export const DELETE_OFFER_REQUEST="DELETE_OFFER_REQUEST";
export const DELETE_OFFER_SUCCESS="DELETE_OFFER_SUCCESS";
export const DELETE_OFFER_FAIL="DELETE_OFFER_FAIL";

